# Generated by Django 3.2.5 on 2021-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='itmes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='receipt',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
