# Generated by Django 3.2.5 on 2021-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210719_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
